export const routes = {
  home: '/',
  events: '/events',
  pomoc: '/pomoc',
  'for-municipalities': '/for-municipalities',
  'book-event': '/book-event',
  'for-parents': '/for-parents',
  sponsors: '/sponsors',
  impact: '/impact',
  gallery: '/gallery',
  'about-us': '/about-us',
  contact: '/contact',
  volunteering: '/volunteering',
  'privacy-policy': '/privacy-policy',
  'cookies-policy': '/cookies-policy',
} as const;
